spring.application.name=gateway

server.port=9090
logging.pattern.console="%d{HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"

# --- Routes ---
gateway.routes[0].routeId=Auth-Service
gateway.routes[0].pathPrefix=/api
gateway.routes[0].downstreamUrl=http://localhost:8120/api
gateway.routes[0].requiresAuth=false
gateway.routes[0].methods[0]=POST

gateway.routes[1].routeId=League-Service
gateway.routes[1].pathPrefix=/api/v1/leagues
gateway.routes[1].downstreamUrl=http://localhost:8100/api/v1/leagues
gateway.routes[1].requiresAuth=true

gateway.routes[2].routeId=Stock-Market-Service
gateway.routes[2].pathPrefix=/api/v1/stocks
gateway.routes[2].downstreamUrl=http://localhost:8130/api/v1/stocks
gateway.routes[2].requiresAuth=true

gateway.routes[3].routeId=Transaction-Service
gateway.routes[3].pathPrefix=/api/v1/wallets
gateway.routes[3].downstreamUrl=http://localhost:8110/api/v1/wallets
gateway.routes[3].requiresAuth=true

gateway.routes[4].routeId=Portfolio-Service
gateway.routes[4].pathPrefix=/api/v1/portfolio
gateway.routes[4].downstreamUrl=http://localhost:8140/api/v1/portfolio
gateway.routes[4].requiresAuth=true

# --- JWT Secret Key ---
auth.jwt.secret=${JWT_SECRET_KEY}

# --- JWT Issuer ---
auth.jwt.issuer=Orchard

# --- Timeouts ---
gateway.connect-timeout-ms=3000
gateway.read-timeout-ms=10000

# --- Rate Limiting ---
rate-limiting.default-capacity=20
rate-limiting.default-refill-rate=2

spring.config.import=optional:file:.env[.properties],optional:file:../.env[.properties]
