spring.application.name=gateway

server.port=9090
logging.pattern.console="%d{HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"

gateway.routes[0].routeId=Ingestion-Service
gateway.routes[0].pathPrefix=/ingestion
gateway.routes[0].downstreamUrl=http://localhost:8080/ingestion
gateway.routes[0].requiresAuth=false
gateway.routes[0].rateLimit=10

gateway.routes[1].routeId=League-Service
gateway.routes[1].pathPrefix=/league
gateway.routes[1].downstreamUrl=http://localhost:8080/league
gateway.routes[1].requiresAuth=true
gateway.routes[1].rateLimit=10

gateway.routes[2].routeId=League-Service
gateway.routes[2].pathPrefix=/league/admin
gateway.routes[2].downstreamUrl=http://localhost:8080/league/admin
gateway.routes[2].requiresAuth=true
gateway.routes[2].rateLimit=10

